name: eshop-on-web
version: 1.0.0
summary: eShop Azure Environment
description: Deploys all the Azure resources required to deploy the eShop project
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: name
    name: name
    description: 'Name of the Web App'
    type: string
    required: true