name: app-service-and-sql-db
summary: Create an Azure App Service and SQL DB using Bicep
description: Deploys an Azure Web App and SQL Database
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: name
    name: name
    description: 'Name of the Web App'
    type: string
    required: true